# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/jpesquetinif/yocto/poky/meta \
  /home/jpesquetinif/yocto/poky/meta-poky \
  /home/jpesquetinif/yocto/poky/meta-yocto-bsp \
  /home/jpesquetinif/yocto/meta-myapp \
  /home/jpesquetinif/yocto/meta-rust-bin \
  /home/jpesquetinif/yocto/meta-openembedded/meta-oe \
  /home/jpesquetinif/yocto/meta-openembedded/meta-python \
  /home/jpesquetinif/yocto/meta-openembedded/meta-multimedia \
  "
